feat: basic jacoco backend

diff --git a/bin/jqf-afl-fuzz b/bin/jqf-afl-fuzz
--- a/bin/jqf-afl-fuzz
+++ b/bin/jqf-afl-fuzz
@@ -164,16 +164,18 @@ export AFL_NO_AFFINITY=1
 export AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
 export AFL_SKIP_CPUFREQ=1
 
+
+# Don't do pilot run
 # Do a pilot run to make sure that the class/method are JQF fuzz targets
-echo -n "Performing pilot run...."
-tmp_out=$(mktemp $JQF_TMP_DIR/jqf-pilot.XXX)
-head -c 1024 /dev/urandom | "$BIN_DIR/jqf-repro" "$class" "$method" /dev/stdin 1> $tmp_out 2>&1
-if [ "$?" -ne 0 ]; then
-  echo "  ERROR: Pilot run failed!!!"
-  cat "$tmp_out"
-  exit 3
-fi
-echo "  Pilot run success! Launching AFL now..."
+# echo -n "Performing pilot run...."
+# tmp_out=$(mktemp $JQF_TMP_DIR/jqf-pilot.XXX)
+# head -c 1024 /dev/urandom | "$BIN_DIR/jqf-repro" "$class" "$method" /dev/stdin 1> $tmp_out 2>&1
+# if [ "$?" -ne 0 ]; then
+#   echo "  ERROR: Pilot run failed!!!"
+#   cat "$tmp_out"
+#   exit 3
+# fi
+# echo "  Pilot run success! Launching AFL now..."
 
 # Ready to go
 exec "$AFL_FUZZ" $afl_options "$target" $target_options "$class" "$method" @@
